### PR TITLE
translation support

### PR DESCRIPTION
**Pull request by FaceDeer**
Hope you don't mind, I've been working on a Python script for automating translation file generation and Cloudlands was the first mod that came to mind that I knew had a string with [[square bracket delimiters]]. So I used it as a testbed.

I included the python script, in theory you can just re-run it to update the translation files whenever you make any change to user-facing text. [here's the repo where I'm working on the script itself](https://github.com/FaceDeer/update_translations).

### CODE REVIEW

**Comment by FaceDeer** [comment]
Might want to hold off on merging this for a bit, I'm getting feedback on the i18n script and there's a lot of fiddling going on right now. I don't think there's anything technically wrong with the file as it exists here, just a matter of formatting it consistently.

**Comment by Treer** [comment]
Thanks. I somehow missed this PR, will look at it this weekend.

**Comment by FaceDeer** [comment]
No rush, I know how it can be with pull requests slipping under the radar. :)

I think the i18n script has stabilized, it's been a while since the folks working on it with me have said anything or filed any issues. I've used it on a bunch of mods and there've been no systemic bugs with any of them either.

**Comment by Treer** [comment]
Shouldn't "https://github.com/FaceDeer/update_translations" be included in the comment at the head of  i18n.py?

**Comment by FaceDeer** [comment]
I was hoping that I wouldn't be the long-term maintainer of the script, but I guess since I seem to be saddled with that right now I might as well. Always a risk one takes when volunteering to help out I guess. :)

**Pull request merged**
